#!/bin/bash

if [ -z "$PYFILE" ]; then
    echo "Environment variable PYFILE is not set."
    exit 1
fi

if [ ! -f "$PYFILE" ]; then
    echo "File specified in PYFILE does not exist."
    exit 1
fi

python3 $PYFILE
